// Generated by rstantools.  Do not edit by hand.

/*
    countmodels is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    countmodels is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with countmodels.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.37.0-rc2
#include <stan/model/model_header.hpp>
namespace model_reg_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 182> locations_array__ =
  {" (found before start of program)",
  " (in 'reg', line 181, column 2 to column 21)",
  " (in 'reg', line 182, column 2 to column 23)",
  " (in 'reg', line 185, column 2 to column 17)",
  " (in 'reg', line 189, column 4 to column 43)",
  " (in 'reg', line 190, column 4 to column 58)",
  " (in 'reg', line 188, column 7 to line 191, column 3)",
  " (in 'reg', line 187, column 4 to column 34)",
  " (in 'reg', line 186, column 10 to line 188, column 3)",
  " (in 'reg', line 186, column 2 to line 191, column 3)",
  " (in 'reg', line 195, column 8 to column 53)",
  " (in 'reg', line 197, column 12 to column 43)",
  " (in 'reg', line 196, column 21 to line 198, column 9)",
  " (in 'reg', line 196, column 8 to line 198, column 9)",
  " (in 'reg', line 194, column 19 to line 199, column 5)",
  " (in 'reg', line 194, column 4 to line 199, column 5)",
  " (in 'reg', line 204, column 8 to column 66)",
  " (in 'reg', line 203, column 10 to line 205, column 5)",
  " (in 'reg', line 201, column 8 to column 60)",
  " (in 'reg', line 200, column 17 to line 203, column 5)",
  " (in 'reg', line 200, column 4 to line 205, column 5)",
  " (in 'reg', line 166, column 2 to column 17)",
  " (in 'reg', line 167, column 2 to column 17)",
  " (in 'reg', line 168, column 8 to column 9)",
  " (in 'reg', line 168, column 2 to column 26)",
  " (in 'reg', line 169, column 9 to column 10)",
  " (in 'reg', line 169, column 12 to column 13)",
  " (in 'reg', line 169, column 2 to column 17)",
  " (in 'reg', line 170, column 2 to column 33)",
  " (in 'reg', line 171, column 2 to column 33)",
  " (in 'reg', line 172, column 13 to column 14)",
  " (in 'reg', line 172, column 2 to column 23)",
  " (in 'reg', line 173, column 18 to column 19)",
  " (in 'reg', line 173, column 2 to column 26)",
  " (in 'reg', line 174, column 2 to column 33)",
  " (in 'reg', line 175, column 9 to column 10)",
  " (in 'reg', line 175, column 2 to column 20)",
  " (in 'reg', line 176, column 9 to column 10)",
  " (in 'reg', line 176, column 11 to column 12)",
  " (in 'reg', line 176, column 2 to column 25)",
  " (in 'reg', line 177, column 2 to column 26)",
  " (in 'reg', line 178, column 2 to column 26)",
  " (in 'reg', line 181, column 9 to column 10)",
  " (in 'reg', line 185, column 9 to column 10)",
  " (in 'reg', line 4, column 2 to column 27)",
  " (in 'reg', line 5, column 9 to column 10)",
  " (in 'reg', line 5, column 2 to column 14)",
  " (in 'reg', line 7, column 5 to column 30)",
  " (in 'reg', line 6, column 15 to line 8, column 3)",
  " (in 'reg', line 6, column 2 to line 8, column 3)",
  " (in 'reg', line 9, column 2 to column 12)",
  " (in 'reg', line 3, column 28 to line 10, column 1)",
  " (in 'reg', line 23, column 7 to column 30)",
  " (in 'reg', line 22, column 22 to column 41)",
  " (in 'reg', line 22, column 7 to line 23, column 30)",
  " (in 'reg', line 21, column 22 to column 32)",
  " (in 'reg', line 21, column 7 to line 23, column 30)",
  " (in 'reg', line 20, column 22 to column 37)",
  " (in 'reg', line 20, column 2 to line 23, column 30)",
  " (in 'reg', line 24, column 2 to column 12)",
  " (in 'reg', line 19, column 44 to line 25, column 1)",
  " (in 'reg', line 41, column 7 to column 30)",
  " (in 'reg', line 40, column 22 to column 52)",
  " (in 'reg', line 40, column 7 to line 41, column 30)",
  " (in 'reg', line 39, column 22 to column 46)",
  " (in 'reg', line 39, column 7 to line 41, column 30)",
  " (in 'reg', line 38, column 22 to column 38)",
  " (in 'reg', line 38, column 7 to line 41, column 30)",
  " (in 'reg', line 37, column 22 to column 45)",
  " (in 'reg', line 37, column 2 to line 41, column 30)",
  " (in 'reg', line 42, column 2 to column 12)",
  " (in 'reg', line 35, column 41 to line 43, column 1)",
  " (in 'reg', line 47, column 2 to column 26)",
  " (in 'reg', line 48, column 9 to column 10)",
  " (in 'reg', line 48, column 2 to column 18)",
  " (in 'reg', line 49, column 9 to column 10)",
  " (in 'reg', line 49, column 2 to column 25)",
  " (in 'reg', line 50, column 9 to column 10)",
  " (in 'reg', line 50, column 2 to column 45)",
  " (in 'reg', line 52, column 4 to column 42)",
  " (in 'reg', line 51, column 15 to line 53, column 3)",
  " (in 'reg', line 51, column 2 to line 53, column 3)",
  " (in 'reg', line 56, column 0 to column 13)",
  " (in 'reg', line 46, column 70 to line 57, column 1)",
  " (in 'reg', line 60, column 2 to column 26)",
  " (in 'reg', line 61, column 9 to column 10)",
  " (in 'reg', line 61, column 2 to column 18)",
  " (in 'reg', line 62, column 9 to column 10)",
  " (in 'reg', line 62, column 2 to column 25)",
  " (in 'reg', line 63, column 9 to column 10)",
  " (in 'reg', line 63, column 2 to column 45)",
  " (in 'reg', line 64, column 9 to column 10)",
  " (in 'reg', line 64, column 2 to column 31)",
  " (in 'reg', line 67, column 4 to column 57)",
  " (in 'reg', line 66, column 15 to line 68, column 3)",
  " (in 'reg', line 66, column 2 to line 68, column 3)",
  " (in 'reg', line 71, column 0 to column 13)",
  " (in 'reg', line 59, column 80 to line 72, column 1)",
  " (in 'reg', line 76, column 2 to column 26)",
  " (in 'reg', line 77, column 9 to column 10)",
  " (in 'reg', line 77, column 2 to column 18)",
  " (in 'reg', line 78, column 9 to column 10)",
  " (in 'reg', line 78, column 2 to column 25)",
  " (in 'reg', line 79, column 9 to column 10)",
  " (in 'reg', line 79, column 2 to column 24)",
  " (in 'reg', line 80, column 9 to column 10)",
  " (in 'reg', line 80, column 2 to column 45)",
  " (in 'reg', line 81, column 9 to column 10)",
  " (in 'reg', line 81, column 2 to column 45)",
  " (in 'reg', line 87, column 6 to column 62)",
  " (in 'reg', line 86, column 9 to line 88, column 5)",
  " (in 'reg', line 85, column 6 to column 91)",
  " (in 'reg', line 84, column 17 to line 86, column 5)",
  " (in 'reg', line 84, column 4 to line 88, column 5)",
  " (in 'reg', line 83, column 15 to line 89, column 3)",
  " (in 'reg', line 83, column 2 to line 89, column 3)",
  " (in 'reg', line 93, column 0 to column 13)",
  " (in 'reg', line 75, column 104 to line 94, column 1)",
  " (in 'reg', line 97, column 2 to column 26)",
  " (in 'reg', line 98, column 9 to column 10)",
  " (in 'reg', line 98, column 2 to column 18)",
  " (in 'reg', line 99, column 9 to column 10)",
  " (in 'reg', line 99, column 2 to column 25)",
  " (in 'reg', line 100, column 9 to column 10)",
  " (in 'reg', line 100, column 2 to column 24)",
  " (in 'reg', line 101, column 9 to column 10)",
  " (in 'reg', line 101, column 2 to column 45)",
  " (in 'reg', line 102, column 9 to column 10)",
  " (in 'reg', line 102, column 2 to column 45)",
  " (in 'reg', line 108, column 6 to column 85)",
  " (in 'reg', line 107, column 9 to line 109, column 5)",
  " (in 'reg', line 106, column 6 to column 31)",
  " (in 'reg', line 105, column 17 to line 107, column 5)",
  " (in 'reg', line 105, column 4 to line 109, column 5)",
  " (in 'reg', line 104, column 15 to line 110, column 3)",
  " (in 'reg', line 104, column 2 to line 110, column 3)",
  " (in 'reg', line 114, column 0 to column 13)",
  " (in 'reg', line 96, column 104 to line 115, column 1)",
  " (in 'reg', line 119, column 2 to column 26)",
  " (in 'reg', line 120, column 9 to column 10)",
  " (in 'reg', line 120, column 2 to column 18)",
  " (in 'reg', line 121, column 9 to column 10)",
  " (in 'reg', line 121, column 2 to column 25)",
  " (in 'reg', line 122, column 9 to column 10)",
  " (in 'reg', line 122, column 2 to column 24)",
  " (in 'reg', line 123, column 9 to column 10)",
  " (in 'reg', line 123, column 2 to column 45)",
  " (in 'reg', line 124, column 9 to column 10)",
  " (in 'reg', line 124, column 2 to column 45)",
  " (in 'reg', line 125, column 9 to column 10)",
  " (in 'reg', line 125, column 2 to column 31)",
  " (in 'reg', line 131, column 6 to column 77)",
  " (in 'reg', line 130, column 9 to line 132, column 5)",
  " (in 'reg', line 129, column 6 to column 105)",
  " (in 'reg', line 128, column 17 to line 130, column 5)",
  " (in 'reg', line 128, column 4 to line 132, column 5)",
  " (in 'reg', line 127, column 15 to line 133, column 3)",
  " (in 'reg', line 127, column 2 to line 133, column 3)",
  " (in 'reg', line 137, column 0 to column 13)",
  " (in 'reg', line 118, column 115 to line 138, column 1)",
  " (in 'reg', line 141, column 2 to column 26)",
  " (in 'reg', line 142, column 9 to column 10)",
  " (in 'reg', line 142, column 2 to column 18)",
  " (in 'reg', line 143, column 9 to column 10)",
  " (in 'reg', line 143, column 2 to column 25)",
  " (in 'reg', line 144, column 9 to column 10)",
  " (in 'reg', line 144, column 2 to column 24)",
  " (in 'reg', line 145, column 9 to column 10)",
  " (in 'reg', line 145, column 2 to column 45)",
  " (in 'reg', line 146, column 9 to column 10)",
  " (in 'reg', line 146, column 2 to column 45)",
  " (in 'reg', line 147, column 9 to column 10)",
  " (in 'reg', line 147, column 2 to column 31)",
  " (in 'reg', line 153, column 6 to column 100)",
  " (in 'reg', line 152, column 9 to line 154, column 5)",
  " (in 'reg', line 151, column 6 to column 31)",
  " (in 'reg', line 150, column 17 to line 152, column 5)",
  " (in 'reg', line 150, column 4 to line 154, column 5)",
  " (in 'reg', line 149, column 15 to line 155, column 3)",
  " (in 'reg', line 149, column 2 to line 155, column 3)",
  " (in 'reg', line 159, column 0 to column 13)",
  " (in 'reg', line 140, column 116 to line 160, column 1)"};
template <typename T0__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,1>
inv_logit2(const T0__& lp_arg__, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              std::is_integral<std::decay_t<T1__>>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,1>
linkinv_poisson(const T0__& lp_arg__, const T1__& link, std::ostream*
                pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              std::is_integral<std::decay_t<T1__>>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,1>
linkinv_bern(const T0__& lp_arg__, const T1__& link, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              std::is_integral<std::decay_t<T3__>>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>>,-1,1>
loglik_poisson(const T0__& y, const T1__& X_arg__, const T2__& beta_arg__,
               const T3__& link1, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T3__>>>,
                              std::is_integral<std::decay_t<T4__>>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, T3__>,-1,1>
loglik_negbin(const T0__& y, const T1__& X_arg__, const T2__& beta_arg__,
              const T3__& theta, const T4__& link1, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              std::is_integral<std::decay_t<T5__>>,
                              std::is_integral<std::decay_t<T6__>>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>>,-1,1>
loglik_zipoisson(const T0__& y, const T1__& X_arg__, const T2__& Z_arg__,
                 const T3__& beta_arg__, const T4__& psi_arg__, const T5__&
                 link1, const T6__& link2, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              std::is_integral<std::decay_t<T5__>>,
                              std::is_integral<std::decay_t<T6__>>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>>,-1,1>
loglik_zapoisson(const T0__& y, const T1__& X_arg__, const T2__& Z_arg__,
                 const T3__& beta_arg__, const T4__& psi_arg__, const T5__&
                 link1, const T6__& link2, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__, typename T7__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              stan::math::disjunction<stan::is_autodiff<T5__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T5__>>>,
                              std::is_integral<std::decay_t<T6__>>,
                              std::is_integral<std::decay_t<T7__>>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>, T5__>,-1,1>
loglik_zinegbin(const T0__& y, const T1__& X_arg__, const T2__& Z_arg__,
                const T3__& beta_arg__, const T4__& psi_arg__, const T5__&
                theta, const T6__& link1, const T7__& link2, std::ostream*
                pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__, typename T7__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              stan::math::disjunction<stan::is_autodiff<T5__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T5__>>>,
                              std::is_integral<std::decay_t<T6__>>,
                              std::is_integral<std::decay_t<T7__>>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>, T5__>,-1,1>
loglik_zanegbin(const T0__& y, const T1__& X_arg__, const T2__& Z_arg__,
                const T3__& beta_arg__, const T4__& psi_arg__, const T5__&
                theta, const T6__& link1, const T7__& link2, std::ostream*
                pstream__);
// vector inv_logit2(vector)
template <typename T0__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,1>
inv_logit2(const T0__& lp_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& lp = stan::math::to_ref(lp_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 44;
    n = stan::math::num_elements(lp);
    current_statement__ = 45;
    stan::math::validate_non_negative_index("x", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> x =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 49;
    for (int i = 1; i <= n; ++i) {
      current_statement__ = 47;
      stan::model::assign(x, (1 / (1 +
        stan::math::exp(
          -(stan::model::rvalue(lp, "lp", stan::model::index_uni(i)))))),
        "assigning variable x", stan::model::index_uni(i));
    }
    current_statement__ = 50;
    return x;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// vector linkinv_poisson(vector, int)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              std::is_integral<std::decay_t<T1__>>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,1>
linkinv_poisson(const T0__& lp_arg__, const T1__& link, std::ostream*
                pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& lp = stan::math::to_ref(lp_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 58;
    if (stan::math::logical_eq(link, 1)) {
      current_statement__ = 57;
      return stan::math::exp(lp);
    } else {
      current_statement__ = 56;
      if (stan::math::logical_eq(link, 2)) {
        current_statement__ = 55;
        return lp;
      } else {
        current_statement__ = 54;
        if (stan::math::logical_eq(link, 3)) {
          current_statement__ = 53;
          return stan::math::square(lp);
        } else {
          current_statement__ = 52;
          {
            std::stringstream errmsg_stream__;
            stan::math::stan_print(&errmsg_stream__, "Invalid link");
            throw std::domain_error(errmsg_stream__.str());
          }
        }
      }
    }
    current_statement__ = 59;
    return lp;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// vector linkinv_bern(vector, int)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              std::is_integral<std::decay_t<T1__>>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,1>
linkinv_bern(const T0__& lp_arg__, const T1__& link, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& lp = stan::math::to_ref(lp_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 69;
    if (stan::math::logical_eq(link, 1)) {
      current_statement__ = 68;
      return inv_logit2(lp, pstream__);
    } else {
      current_statement__ = 67;
      if (stan::math::logical_eq(link, 2)) {
        current_statement__ = 66;
        return stan::math::Phi(lp);
      } else {
        current_statement__ = 65;
        if (stan::math::logical_eq(link, 3)) {
          current_statement__ = 64;
          return stan::math::inv_cloglog(lp);
        } else {
          current_statement__ = 63;
          if (stan::math::logical_eq(link, 4)) {
            current_statement__ = 62;
            return stan::math::add(
                     stan::math::divide(stan::math::atan(lp),
                       stan::math::pi()), 0.5);
          } else {
            current_statement__ = 61;
            {
              std::stringstream errmsg_stream__;
              stan::math::stan_print(&errmsg_stream__, "Invalid link");
              throw std::domain_error(errmsg_stream__.str());
            }
          }
        }
      }
    }
    current_statement__ = 70;
    return lp;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// vector loglik_poisson(array[] int, matrix, vector, int)
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              std::is_integral<std::decay_t<T3__>>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>>,-1,1>
loglik_poisson(const T0__& y, const T1__& X_arg__, const T2__& beta_arg__,
               const T3__& link1, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& X = stan::math::to_ref(X_arg__);
  const auto& beta = stan::math::to_ref(beta_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 72;
    n = stan::math::num_elements(y);
    current_statement__ = 73;
    stan::math::validate_non_negative_index("lprob", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lprob =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 75;
    stan::math::validate_non_negative_index("lp1", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp1 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 76;
    stan::model::assign(lp1, stan::math::multiply(X, beta),
      "assigning variable lp1");
    current_statement__ = 77;
    stan::math::validate_non_negative_index("mu", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> mu =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 78;
    stan::model::assign(mu, linkinv_poisson(lp1, link1, pstream__),
      "assigning variable mu");
    current_statement__ = 81;
    for (int i = 1; i <= n; ++i) {
      current_statement__ = 79;
      stan::model::assign(lprob,
        stan::math::poisson_lpmf<false>(
          stan::model::rvalue(y, "y", stan::model::index_uni(i)),
          stan::model::rvalue(mu, "mu", stan::model::index_uni(i))),
        "assigning variable lprob", stan::model::index_uni(i));
    }
    current_statement__ = 82;
    return lprob;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// vector loglik_negbin(array[] int, matrix, vector, real, int)
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T3__>>>,
                              std::is_integral<std::decay_t<T4__>>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, T3__>,-1,1>
loglik_negbin(const T0__& y, const T1__& X_arg__, const T2__& beta_arg__,
              const T3__& theta, const T4__& link1, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>, T3__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& X = stan::math::to_ref(X_arg__);
  const auto& beta = stan::math::to_ref(beta_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 84;
    n = stan::math::num_elements(y);
    current_statement__ = 85;
    stan::math::validate_non_negative_index("lprob", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lprob =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 87;
    stan::math::validate_non_negative_index("lp1", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp1 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 88;
    stan::model::assign(lp1, stan::math::multiply(X, beta),
      "assigning variable lp1");
    current_statement__ = 89;
    stan::math::validate_non_negative_index("mu", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> mu =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 90;
    stan::model::assign(mu, linkinv_poisson(lp1, link1, pstream__),
      "assigning variable mu");
    current_statement__ = 91;
    stan::math::validate_non_negative_index("alpha", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> alpha =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 92;
    stan::model::assign(alpha, stan::math::multiply(mu, theta),
      "assigning variable alpha");
    current_statement__ = 95;
    for (int i = 1; i <= n; ++i) {
      current_statement__ = 93;
      stan::model::assign(lprob,
        stan::math::neg_binomial_lpmf<false>(
          stan::model::rvalue(y, "y", stan::model::index_uni(i)),
          stan::model::rvalue(alpha, "alpha", stan::model::index_uni(i)),
          theta), "assigning variable lprob", stan::model::index_uni(i));
    }
    current_statement__ = 96;
    return lprob;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
/* vector
   loglik_zipoisson(array[] int, matrix, matrix, vector, vector, int, int)
 */
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              std::is_integral<std::decay_t<T5__>>,
                              std::is_integral<std::decay_t<T6__>>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>>,-1,1>
loglik_zipoisson(const T0__& y, const T1__& X_arg__, const T2__& Z_arg__,
                 const T3__& beta_arg__, const T4__& psi_arg__, const T5__&
                 link1, const T6__& link2, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>,
                             stan::base_type_t<T4__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& X = stan::math::to_ref(X_arg__);
  const auto& Z = stan::math::to_ref(Z_arg__);
  const auto& beta = stan::math::to_ref(beta_arg__);
  const auto& psi = stan::math::to_ref(psi_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 98;
    n = stan::math::num_elements(y);
    current_statement__ = 99;
    stan::math::validate_non_negative_index("lprob", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lprob =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 101;
    stan::math::validate_non_negative_index("lp1", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp1 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 102;
    stan::model::assign(lp1, stan::math::multiply(X, beta),
      "assigning variable lp1");
    current_statement__ = 103;
    stan::math::validate_non_negative_index("lp2", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp2 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 104;
    stan::model::assign(lp2, stan::math::multiply(Z, psi),
      "assigning variable lp2");
    current_statement__ = 105;
    stan::math::validate_non_negative_index("mu", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> mu =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 106;
    stan::model::assign(mu, linkinv_poisson(lp1, link1, pstream__),
      "assigning variable mu");
    current_statement__ = 107;
    stan::math::validate_non_negative_index("omega", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> omega =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 108;
    stan::model::assign(omega, linkinv_bern(lp2, link2, pstream__),
      "assigning variable omega");
    current_statement__ = 115;
    for (int i = 1; i <= n; ++i) {
      current_statement__ = 113;
      if (stan::math::logical_eq(
            stan::model::rvalue(y, "y", stan::model::index_uni(i)), 0)) {
        current_statement__ = 111;
        stan::model::assign(lprob,
          stan::math::log_sum_exp(
            stan::math::log(
              stan::model::rvalue(omega, "omega", stan::model::index_uni(i))),
            (stan::math::log1m(
               stan::model::rvalue(omega, "omega", stan::model::index_uni(i)))
            +
            stan::math::poisson_lpmf<false>(
              stan::model::rvalue(y, "y", stan::model::index_uni(i)),
              stan::model::rvalue(mu, "mu", stan::model::index_uni(i))))),
          "assigning variable lprob", stan::model::index_uni(i));
      } else {
        current_statement__ = 109;
        stan::model::assign(lprob,
          (stan::math::log1m(
             stan::model::rvalue(omega, "omega", stan::model::index_uni(i)))
          +
          stan::math::poisson_lpmf<false>(
            stan::model::rvalue(y, "y", stan::model::index_uni(i)),
            stan::model::rvalue(mu, "mu", stan::model::index_uni(i)))),
          "assigning variable lprob", stan::model::index_uni(i));
      }
    }
    current_statement__ = 116;
    return lprob;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
/* vector
   loglik_zapoisson(array[] int, matrix, matrix, vector, vector, int, int)
 */
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              std::is_integral<std::decay_t<T5__>>,
                              std::is_integral<std::decay_t<T6__>>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>>,-1,1>
loglik_zapoisson(const T0__& y, const T1__& X_arg__, const T2__& Z_arg__,
                 const T3__& beta_arg__, const T4__& psi_arg__, const T5__&
                 link1, const T6__& link2, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>,
                             stan::base_type_t<T4__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& X = stan::math::to_ref(X_arg__);
  const auto& Z = stan::math::to_ref(Z_arg__);
  const auto& beta = stan::math::to_ref(beta_arg__);
  const auto& psi = stan::math::to_ref(psi_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 118;
    n = stan::math::num_elements(y);
    current_statement__ = 119;
    stan::math::validate_non_negative_index("lprob", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lprob =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 121;
    stan::math::validate_non_negative_index("lp1", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp1 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 122;
    stan::model::assign(lp1, stan::math::multiply(X, beta),
      "assigning variable lp1");
    current_statement__ = 123;
    stan::math::validate_non_negative_index("lp2", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp2 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 124;
    stan::model::assign(lp2, stan::math::multiply(Z, psi),
      "assigning variable lp2");
    current_statement__ = 125;
    stan::math::validate_non_negative_index("mu", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> mu =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 126;
    stan::model::assign(mu, linkinv_poisson(lp1, link1, pstream__),
      "assigning variable mu");
    current_statement__ = 127;
    stan::math::validate_non_negative_index("omega", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> omega =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 128;
    stan::model::assign(omega, linkinv_bern(lp2, link2, pstream__),
      "assigning variable omega");
    current_statement__ = 135;
    for (int i = 1; i <= n; ++i) {
      current_statement__ = 133;
      if (stan::math::logical_eq(
            stan::model::rvalue(y, "y", stan::model::index_uni(i)), 0)) {
        current_statement__ = 131;
        stan::model::assign(lprob,
          stan::math::log(
            stan::model::rvalue(omega, "omega", stan::model::index_uni(i))),
          "assigning variable lprob", stan::model::index_uni(i));
      } else {
        current_statement__ = 129;
        stan::model::assign(lprob,
          ((stan::math::log1m(
              stan::model::rvalue(omega, "omega", stan::model::index_uni(i)))
          +
          stan::math::poisson_lpmf<false>(
            stan::model::rvalue(y, "y", stan::model::index_uni(i)),
            stan::model::rvalue(mu, "mu", stan::model::index_uni(i)))) -
          stan::math::log1m_exp(
            -(stan::model::rvalue(omega, "omega", stan::model::index_uni(i))))),
          "assigning variable lprob", stan::model::index_uni(i));
      }
    }
    current_statement__ = 136;
    return lprob;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
/* vector
   loglik_zinegbin(array[] int, matrix, matrix, vector, vector, real, int,
  int)
 */
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__, typename T7__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              stan::math::disjunction<stan::is_autodiff<T5__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T5__>>>,
                              std::is_integral<std::decay_t<T6__>>,
                              std::is_integral<std::decay_t<T7__>>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>, T5__>,-1,1>
loglik_zinegbin(const T0__& y, const T1__& X_arg__, const T2__& Z_arg__,
                const T3__& beta_arg__, const T4__& psi_arg__, const T5__&
                theta, const T6__& link1, const T7__& link2, std::ostream*
                pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>,
                             stan::base_type_t<T4__>, T5__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& X = stan::math::to_ref(X_arg__);
  const auto& Z = stan::math::to_ref(Z_arg__);
  const auto& beta = stan::math::to_ref(beta_arg__);
  const auto& psi = stan::math::to_ref(psi_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 138;
    n = stan::math::num_elements(y);
    current_statement__ = 139;
    stan::math::validate_non_negative_index("lprob", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lprob =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 141;
    stan::math::validate_non_negative_index("lp1", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp1 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 142;
    stan::model::assign(lp1, stan::math::multiply(X, beta),
      "assigning variable lp1");
    current_statement__ = 143;
    stan::math::validate_non_negative_index("lp2", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp2 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 144;
    stan::model::assign(lp2, stan::math::multiply(Z, psi),
      "assigning variable lp2");
    current_statement__ = 145;
    stan::math::validate_non_negative_index("mu", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> mu =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 146;
    stan::model::assign(mu, linkinv_poisson(lp1, link1, pstream__),
      "assigning variable mu");
    current_statement__ = 147;
    stan::math::validate_non_negative_index("omega", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> omega =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 148;
    stan::model::assign(omega, linkinv_bern(lp2, link2, pstream__),
      "assigning variable omega");
    current_statement__ = 149;
    stan::math::validate_non_negative_index("alpha", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> alpha =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 150;
    stan::model::assign(alpha, stan::math::multiply(mu, theta),
      "assigning variable alpha");
    current_statement__ = 157;
    for (int i = 1; i <= n; ++i) {
      current_statement__ = 155;
      if (stan::math::logical_eq(
            stan::model::rvalue(y, "y", stan::model::index_uni(i)), 0)) {
        current_statement__ = 153;
        stan::model::assign(lprob,
          stan::math::log_sum_exp(
            stan::math::log(
              stan::model::rvalue(omega, "omega", stan::model::index_uni(i))),
            (stan::math::log1m(
               stan::model::rvalue(omega, "omega", stan::model::index_uni(i)))
            +
            stan::math::neg_binomial_lpmf<false>(
              stan::model::rvalue(y, "y", stan::model::index_uni(i)),
              stan::model::rvalue(alpha, "alpha", stan::model::index_uni(i)),
              theta))), "assigning variable lprob", stan::model::index_uni(i));
      } else {
        current_statement__ = 151;
        stan::model::assign(lprob,
          (stan::math::log1m(
             stan::model::rvalue(omega, "omega", stan::model::index_uni(i)))
          +
          stan::math::neg_binomial_lpmf<false>(
            stan::model::rvalue(y, "y", stan::model::index_uni(i)),
            stan::model::rvalue(alpha, "alpha", stan::model::index_uni(i)),
            theta)), "assigning variable lprob", stan::model::index_uni(i));
      }
    }
    current_statement__ = 158;
    return lprob;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
/* vector
   loglik_zanegbin(array[] int, matrix, matrix, vector, vector, real, int,
  int)
 */
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__, typename T7__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              stan::math::disjunction<stan::is_autodiff<T5__>,
                                                      std::is_floating_point<
                                                      std::decay_t<T5__>>>,
                              std::is_integral<std::decay_t<T6__>>,
                              std::is_integral<std::decay_t<T7__>>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>, T5__>,-1,1>
loglik_zanegbin(const T0__& y, const T1__& X_arg__, const T2__& Z_arg__,
                const T3__& beta_arg__, const T4__& psi_arg__, const T5__&
                theta, const T6__& link1, const T7__& link2, std::ostream*
                pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>,
                             stan::base_type_t<T4__>, T5__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& X = stan::math::to_ref(X_arg__);
  const auto& Z = stan::math::to_ref(Z_arg__);
  const auto& beta = stan::math::to_ref(beta_arg__);
  const auto& psi = stan::math::to_ref(psi_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 160;
    n = stan::math::num_elements(y);
    current_statement__ = 161;
    stan::math::validate_non_negative_index("lprob", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lprob =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 163;
    stan::math::validate_non_negative_index("lp1", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp1 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 164;
    stan::model::assign(lp1, stan::math::multiply(X, beta),
      "assigning variable lp1");
    current_statement__ = 165;
    stan::math::validate_non_negative_index("lp2", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp2 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 166;
    stan::model::assign(lp2, stan::math::multiply(Z, psi),
      "assigning variable lp2");
    current_statement__ = 167;
    stan::math::validate_non_negative_index("mu", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> mu =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 168;
    stan::model::assign(mu, linkinv_poisson(lp1, link1, pstream__),
      "assigning variable mu");
    current_statement__ = 169;
    stan::math::validate_non_negative_index("omega", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> omega =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 170;
    stan::model::assign(omega, linkinv_bern(lp2, link2, pstream__),
      "assigning variable omega");
    current_statement__ = 171;
    stan::math::validate_non_negative_index("alpha", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> alpha =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 172;
    stan::model::assign(alpha, stan::math::multiply(mu, theta),
      "assigning variable alpha");
    current_statement__ = 179;
    for (int i = 1; i <= n; ++i) {
      current_statement__ = 177;
      if (stan::math::logical_eq(
            stan::model::rvalue(y, "y", stan::model::index_uni(i)), 0)) {
        current_statement__ = 175;
        stan::model::assign(lprob,
          stan::math::log(
            stan::model::rvalue(omega, "omega", stan::model::index_uni(i))),
          "assigning variable lprob", stan::model::index_uni(i));
      } else {
        current_statement__ = 173;
        stan::model::assign(lprob,
          ((stan::math::log1m(
              stan::model::rvalue(omega, "omega", stan::model::index_uni(i)))
          +
          stan::math::neg_binomial_lpmf<false>(
            stan::model::rvalue(y, "y", stan::model::index_uni(i)),
            stan::model::rvalue(alpha, "alpha", stan::model::index_uni(i)),
            theta)) -
          stan::math::log1m_exp(
            -(stan::model::rvalue(omega, "omega", stan::model::index_uni(i))))),
          "assigning variable lprob", stan::model::index_uni(i));
      }
    }
    current_statement__ = 180;
    return lprob;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_reg final : public model_base_crtp<model_reg> {
private:
  int n;
  int p;
  std::vector<int> y;
  Eigen::Matrix<double,-1,-1> X_data__;
  int link;
  int dist;
  Eigen::Matrix<double,1,-1> x_mean_data__;
  Eigen::Matrix<double,-1,1> x_sd_data__;
  int approach;
  Eigen::Matrix<double,-1,1> mu_beta_data__;
  Eigen::Matrix<double,-1,-1> sigma_beta_data__;
  double a_theta;
  double b_theta;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,1,-1>> x_mean{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> x_sd{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> mu_beta{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> sigma_beta{nullptr, 0, 0};
public:
  ~model_reg() {}
  model_reg(stan::io::var_context& context__, unsigned int random_seed__ = 0,
            std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_reg_namespace::model_reg";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 21;
      context__.validate_dims("data initialization", "n", "int",
        std::vector<size_t>{});
      n = std::numeric_limits<int>::min();
      current_statement__ = 21;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 21;
      stan::math::check_greater_or_equal(function__, "n", n, 1);
      current_statement__ = 22;
      context__.validate_dims("data initialization", "p", "int",
        std::vector<size_t>{});
      p = std::numeric_limits<int>::min();
      current_statement__ = 22;
      p = context__.vals_i("p")[(1 - 1)];
      current_statement__ = 22;
      stan::math::check_greater_or_equal(function__, "p", p, 1);
      current_statement__ = 23;
      stan::math::validate_non_negative_index("y", "n", n);
      current_statement__ = 24;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(n)});
      y = std::vector<int>(n, std::numeric_limits<int>::min());
      current_statement__ = 24;
      y = context__.vals_i("y");
      current_statement__ = 24;
      stan::math::check_greater_or_equal(function__, "y", y, 0);
      current_statement__ = 25;
      stan::math::validate_non_negative_index("X", "n", n);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("X", "p", p);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(n), static_cast<size_t>(p)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(n, p,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), n, p);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 27;
        X_flat__ = context__.vals_r("X");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 28;
      context__.validate_dims("data initialization", "link", "int",
        std::vector<size_t>{});
      link = std::numeric_limits<int>::min();
      current_statement__ = 28;
      link = context__.vals_i("link")[(1 - 1)];
      current_statement__ = 28;
      stan::math::check_greater_or_equal(function__, "link", link, 1);
      current_statement__ = 28;
      stan::math::check_less_or_equal(function__, "link", link, 3);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "dist", "int",
        std::vector<size_t>{});
      dist = std::numeric_limits<int>::min();
      current_statement__ = 29;
      dist = context__.vals_i("dist")[(1 - 1)];
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "dist", dist, 1);
      current_statement__ = 29;
      stan::math::check_less_or_equal(function__, "dist", dist, 2);
      current_statement__ = 30;
      stan::math::validate_non_negative_index("x_mean", "p", p);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "x_mean", "double",
        std::vector<size_t>{static_cast<size_t>(p)});
      x_mean_data__ = Eigen::Matrix<double,1,-1>::Constant(p,
                        std::numeric_limits<double>::quiet_NaN());
      new (&x_mean)
        Eigen::Map<Eigen::Matrix<double,1,-1>>(x_mean_data__.data(), p);
      {
        std::vector<local_scalar_t__> x_mean_flat__;
        current_statement__ = 31;
        x_mean_flat__ = context__.vals_r("x_mean");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          stan::model::assign(x_mean, x_mean_flat__[(pos__ - 1)],
            "assigning variable x_mean", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 32;
      stan::math::validate_non_negative_index("x_sd", "p", p);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "x_sd", "double",
        std::vector<size_t>{static_cast<size_t>(p)});
      x_sd_data__ = Eigen::Matrix<double,-1,1>::Constant(p,
                      std::numeric_limits<double>::quiet_NaN());
      new (&x_sd) Eigen::Map<Eigen::Matrix<double,-1,1>>(x_sd_data__.data(),
        p);
      {
        std::vector<local_scalar_t__> x_sd_flat__;
        current_statement__ = 33;
        x_sd_flat__ = context__.vals_r("x_sd");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          stan::model::assign(x_sd, x_sd_flat__[(pos__ - 1)],
            "assigning variable x_sd", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "x_sd", x_sd, 0);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "approach", "int",
        std::vector<size_t>{});
      approach = std::numeric_limits<int>::min();
      current_statement__ = 34;
      approach = context__.vals_i("approach")[(1 - 1)];
      current_statement__ = 34;
      stan::math::check_greater_or_equal(function__, "approach", approach, 0);
      current_statement__ = 34;
      stan::math::check_less_or_equal(function__, "approach", approach, 1);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("mu_beta", "p", p);
      current_statement__ = 36;
      context__.validate_dims("data initialization", "mu_beta", "double",
        std::vector<size_t>{static_cast<size_t>(p)});
      mu_beta_data__ = Eigen::Matrix<double,-1,1>::Constant(p,
                         std::numeric_limits<double>::quiet_NaN());
      new (&mu_beta)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(mu_beta_data__.data(), p);
      {
        std::vector<local_scalar_t__> mu_beta_flat__;
        current_statement__ = 36;
        mu_beta_flat__ = context__.vals_r("mu_beta");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          stan::model::assign(mu_beta, mu_beta_flat__[(pos__ - 1)],
            "assigning variable mu_beta", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 37;
      stan::math::validate_non_negative_index("sigma_beta", "p", p);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("sigma_beta", "p", p);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "sigma_beta", "double",
        std::vector<size_t>{static_cast<size_t>(p), static_cast<size_t>(p)});
      sigma_beta_data__ = Eigen::Matrix<double,-1,-1>::Constant(p, p,
                            std::numeric_limits<double>::quiet_NaN());
      new (&sigma_beta)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(sigma_beta_data__.data(), p,
        p);
      {
        std::vector<local_scalar_t__> sigma_beta_flat__;
        current_statement__ = 39;
        sigma_beta_flat__ = context__.vals_r("sigma_beta");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= p; ++sym2__) {
            stan::model::assign(sigma_beta, sigma_beta_flat__[(pos__ - 1)],
              "assigning variable sigma_beta",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 40;
      context__.validate_dims("data initialization", "a_theta", "double",
        std::vector<size_t>{});
      a_theta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 40;
      a_theta = context__.vals_r("a_theta")[(1 - 1)];
      current_statement__ = 40;
      stan::math::check_greater_or_equal(function__, "a_theta", a_theta, 0);
      current_statement__ = 41;
      context__.validate_dims("data initialization", "b_theta", "double",
        std::vector<size_t>{});
      b_theta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 41;
      b_theta = context__.vals_r("b_theta")[(1 - 1)];
      current_statement__ = 41;
      stan::math::check_greater_or_equal(function__, "b_theta", b_theta, 0);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("beta_std", "p", p);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("beta", "p", p);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = p + 1;
  }
  inline std::string model_name() const final {
    return "model_reg";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.37.0-rc2",
             "stancflags = --allow-undefined"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ = "model_reg_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto beta_std =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p);
      current_statement__ = 2;
      auto theta =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p, DUMMY_VAR__);
      current_statement__ = 9;
      if (stan::math::logical_eq(p, 1)) {
        current_statement__ = 7;
        stan::model::assign(beta,
          (stan::model::rvalue(beta_std, "beta_std",
             stan::model::index_uni(1)) /
          stan::model::rvalue(x_sd, "x_sd", stan::model::index_uni(1))),
          "assigning variable beta", stan::model::index_uni(1));
      } else {
        current_statement__ = 4;
        stan::model::assign(beta,
          stan::math::elt_divide(
            stan::model::rvalue(beta_std, "beta_std",
              stan::model::index_min_max(2, p)),
            stan::model::rvalue(x_sd, "x_sd",
              stan::model::index_min_max(2, p))), "assigning variable beta",
          stan::model::index_min_max(2, p));
        current_statement__ = 5;
        stan::model::assign(beta,
          ((stan::model::rvalue(beta_std, "beta_std",
              stan::model::index_uni(1)) /
          stan::model::rvalue(x_sd, "x_sd", stan::model::index_uni(1))) -
          stan::math::multiply(
            stan::model::rvalue(x_mean, "x_mean",
              stan::model::index_min_max(2, p)),
            stan::model::rvalue(beta, "beta",
              stan::model::index_min_max(2, p)))), "assigning variable beta",
          stan::model::index_uni(1));
      }
      {
        current_statement__ = 15;
        if (stan::math::logical_eq(approach, 1)) {
          current_statement__ = 10;
          lp_accum__.add(stan::math::multi_normal_lpdf<propto__>(beta_std,
                           mu_beta, sigma_beta));
          current_statement__ = 13;
          if (stan::math::logical_eq(dist, 2)) {
            current_statement__ = 11;
            lp_accum__.add(stan::math::gamma_lpdf<propto__>(theta, a_theta,
                             b_theta));
          }
        }
        current_statement__ = 20;
        if (stan::math::logical_eq(dist, 1)) {
          current_statement__ = 18;
          lp_accum__.add(stan::math::sum(
                           loglik_poisson(y, X, beta_std, link, pstream__)));
        } else {
          current_statement__ = 16;
          lp_accum__.add(stan::math::sum(
                           loglik_negbin(y, X, beta_std, theta, link,
                             pstream__)));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ = "model_reg_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto beta_std =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p);
      current_statement__ = 2;
      auto theta =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p, DUMMY_VAR__);
      current_statement__ = 9;
      if (stan::math::logical_eq(p, 1)) {
        current_statement__ = 7;
        stan::model::assign(beta,
          (stan::model::rvalue(beta_std, "beta_std",
             stan::model::index_uni(1)) /
          stan::model::rvalue(x_sd, "x_sd", stan::model::index_uni(1))),
          "assigning variable beta", stan::model::index_uni(1));
      } else {
        current_statement__ = 4;
        stan::model::assign(beta,
          stan::math::elt_divide(
            stan::model::rvalue(beta_std, "beta_std",
              stan::model::index_min_max(2, p)),
            stan::model::rvalue(x_sd, "x_sd",
              stan::model::index_min_max(2, p))), "assigning variable beta",
          stan::model::index_min_max(2, p));
        current_statement__ = 5;
        stan::model::assign(beta,
          ((stan::model::rvalue(beta_std, "beta_std",
              stan::model::index_uni(1)) /
          stan::model::rvalue(x_sd, "x_sd", stan::model::index_uni(1))) -
          stan::math::multiply(
            stan::model::rvalue(x_mean, "x_mean",
              stan::model::index_min_max(2, p)),
            stan::model::rvalue(beta, "beta",
              stan::model::index_min_max(2, p)))), "assigning variable beta",
          stan::model::index_uni(1));
      }
      {
        current_statement__ = 15;
        if (stan::math::logical_eq(approach, 1)) {
          current_statement__ = 10;
          lp_accum__.add(stan::math::multi_normal_lpdf<propto__>(beta_std,
                           mu_beta, sigma_beta));
          current_statement__ = 13;
          if (stan::math::logical_eq(dist, 2)) {
            current_statement__ = 11;
            lp_accum__.add(stan::math::gamma_lpdf<propto__>(theta, a_theta,
                             b_theta));
          }
        }
        current_statement__ = 20;
        if (stan::math::logical_eq(dist, 1)) {
          current_statement__ = 18;
          lp_accum__.add(stan::math::sum(
                           loglik_poisson(y, X, beta_std, link, pstream__)));
        } else {
          current_statement__ = 16;
          lp_accum__.add(stan::math::sum(
                           loglik_negbin(y, X, beta_std, theta, link,
                             pstream__)));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "model_reg_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto beta_std =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p);
      current_statement__ = 2;
      auto theta =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(p,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(beta_std);
      out__.write(theta);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 9;
      if (stan::math::logical_eq(p, 1)) {
        current_statement__ = 7;
        stan::model::assign(beta,
          (stan::model::rvalue(beta_std, "beta_std",
             stan::model::index_uni(1)) /
          stan::model::rvalue(x_sd, "x_sd", stan::model::index_uni(1))),
          "assigning variable beta", stan::model::index_uni(1));
      } else {
        current_statement__ = 4;
        stan::model::assign(beta,
          stan::math::elt_divide(
            stan::model::rvalue(beta_std, "beta_std",
              stan::model::index_min_max(2, p)),
            stan::model::rvalue(x_sd, "x_sd",
              stan::model::index_min_max(2, p))), "assigning variable beta",
          stan::model::index_min_max(2, p));
        current_statement__ = 5;
        stan::model::assign(beta,
          ((stan::model::rvalue(beta_std, "beta_std",
              stan::model::index_uni(1)) /
          stan::model::rvalue(x_sd, "x_sd", stan::model::index_uni(1))) -
          stan::math::multiply(
            stan::model::rvalue(x_mean, "x_mean",
              stan::model::index_min_max(2, p)),
            stan::model::rvalue(beta, "beta",
              stan::model::index_min_max(2, p)))), "assigning variable beta",
          stan::model::index_uni(1));
      }
      if (emit_transformed_parameters__) {
        out__.write(beta);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> beta_std =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(beta_std,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(p),
        "assigning variable beta_std");
      out__.write(beta_std);
      local_scalar_t__ theta = DUMMY_VAR__;
      current_statement__ = 2;
      theta = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, theta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta_std",
        "double", std::vector<size_t>{static_cast<size_t>(p)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "theta", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta_std =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_std_flat__;
        current_statement__ = 1;
        beta_std_flat__ = context__.vals_r("beta_std");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          stan::model::assign(beta_std, beta_std_flat__[(pos__ - 1)],
            "assigning variable beta_std", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta_std);
      local_scalar_t__ theta = DUMMY_VAR__;
      current_statement__ = 2;
      theta = context__.vals_r("theta")[(1 - 1)];
      out__.write_free_lb(0, theta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta_std", "theta"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"beta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(p)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(p)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_std" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "theta");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_std" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "theta");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta_std\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta_std\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (p + 1);
    const size_t num_transformed = emit_transformed_parameters * (p);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (p + 1);
    const size_t num_transformed = emit_transformed_parameters * (p);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_reg_namespace::model_reg;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_reg_namespace::profiles__;
}
#endif
#endif
