// Generated by rstantools.  Do not edit by hand.

/*
    countmodels is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    countmodels is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with countmodels.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.37.0-rc2
#include <stan/model/model_header.hpp>
namespace model_poisson_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 105> locations_array__ =
  {" (found before start of program)",
  " (in 'poisson', line 117, column 2 to column 17)",
  " (in 'poisson', line 126, column 2 to column 40)",
  " (in 'poisson', line 127, column 2 to column 45)",
  " (in 'poisson', line 120, column 2 to column 50)",
  " (in 'poisson', line 122, column 4 to column 39)",
  " (in 'poisson', line 121, column 17 to line 123, column 3)",
  " (in 'poisson', line 121, column 2 to line 123, column 3)",
  " (in 'poisson', line 105, column 2 to column 17)",
  " (in 'poisson', line 106, column 2 to column 17)",
  " (in 'poisson', line 107, column 8 to column 9)",
  " (in 'poisson', line 107, column 2 to column 17)",
  " (in 'poisson', line 108, column 9 to column 10)",
  " (in 'poisson', line 108, column 12 to column 13)",
  " (in 'poisson', line 108, column 2 to column 17)",
  " (in 'poisson', line 109, column 2 to column 33)",
  " (in 'poisson', line 110, column 13 to column 14)",
  " (in 'poisson', line 110, column 2 to column 23)",
  " (in 'poisson', line 111, column 18 to column 19)",
  " (in 'poisson', line 111, column 2 to column 26)",
  " (in 'poisson', line 112, column 2 to column 33)",
  " (in 'poisson', line 113, column 2 to column 15)",
  " (in 'poisson', line 114, column 2 to column 27)",
  " (in 'poisson', line 117, column 9 to column 10)",
  " (in 'poisson', line 126, column 9 to column 30)",
  " (in 'poisson', line 4, column 2 to column 27)",
  " (in 'poisson', line 5, column 9 to column 10)",
  " (in 'poisson', line 5, column 2 to column 14)",
  " (in 'poisson', line 7, column 5 to column 30)",
  " (in 'poisson', line 6, column 15 to line 8, column 3)",
  " (in 'poisson', line 6, column 2 to line 8, column 3)",
  " (in 'poisson', line 9, column 2 to column 12)",
  " (in 'poisson', line 3, column 28 to line 10, column 1)",
  " (in 'poisson', line 23, column 7 to column 30)",
  " (in 'poisson', line 22, column 22 to column 41)",
  " (in 'poisson', line 22, column 7 to line 23, column 30)",
  " (in 'poisson', line 21, column 22 to column 32)",
  " (in 'poisson', line 21, column 7 to line 23, column 30)",
  " (in 'poisson', line 20, column 22 to column 37)",
  " (in 'poisson', line 20, column 2 to line 23, column 30)",
  " (in 'poisson', line 24, column 2 to column 12)",
  " (in 'poisson', line 19, column 44 to line 25, column 1)",
  " (in 'poisson', line 41, column 7 to column 30)",
  " (in 'poisson', line 40, column 22 to column 52)",
  " (in 'poisson', line 40, column 7 to line 41, column 30)",
  " (in 'poisson', line 39, column 22 to column 46)",
  " (in 'poisson', line 39, column 7 to line 41, column 30)",
  " (in 'poisson', line 38, column 22 to column 38)",
  " (in 'poisson', line 38, column 7 to line 41, column 30)",
  " (in 'poisson', line 37, column 22 to column 45)",
  " (in 'poisson', line 37, column 2 to line 41, column 30)",
  " (in 'poisson', line 42, column 2 to column 12)",
  " (in 'poisson', line 35, column 41 to line 43, column 1)",
  " (in 'poisson', line 47, column 2 to column 26)",
  " (in 'poisson', line 48, column 9 to column 10)",
  " (in 'poisson', line 48, column 2 to column 18)",
  " (in 'poisson', line 49, column 9 to column 10)",
  " (in 'poisson', line 49, column 2 to column 25)",
  " (in 'poisson', line 50, column 9 to column 10)",
  " (in 'poisson', line 50, column 2 to column 45)",
  " (in 'poisson', line 52, column 4 to column 42)",
  " (in 'poisson', line 51, column 15 to line 53, column 3)",
  " (in 'poisson', line 51, column 2 to line 53, column 3)",
  " (in 'poisson', line 56, column 0 to column 13)",
  " (in 'poisson', line 46, column 70 to line 57, column 1)",
  " (in 'poisson', line 60, column 2 to column 26)",
  " (in 'poisson', line 61, column 9 to column 10)",
  " (in 'poisson', line 61, column 2 to column 18)",
  " (in 'poisson', line 62, column 9 to column 10)",
  " (in 'poisson', line 62, column 2 to column 25)",
  " (in 'poisson', line 63, column 9 to column 10)",
  " (in 'poisson', line 63, column 2 to column 24)",
  " (in 'poisson', line 64, column 9 to column 10)",
  " (in 'poisson', line 64, column 2 to column 45)",
  " (in 'poisson', line 65, column 9 to column 10)",
  " (in 'poisson', line 65, column 2 to column 45)",
  " (in 'poisson', line 71, column 6 to column 73)",
  " (in 'poisson', line 70, column 9 to line 72, column 5)",
  " (in 'poisson', line 69, column 6 to column 117)",
  " (in 'poisson', line 68, column 17 to line 70, column 5)",
  " (in 'poisson', line 68, column 4 to line 72, column 5)",
  " (in 'poisson', line 67, column 15 to line 73, column 3)",
  " (in 'poisson', line 67, column 2 to line 73, column 3)",
  " (in 'poisson', line 77, column 0 to column 13)",
  " (in 'poisson', line 59, column 104 to line 78, column 1)",
  " (in 'poisson', line 81, column 2 to column 26)",
  " (in 'poisson', line 82, column 9 to column 10)",
  " (in 'poisson', line 82, column 2 to column 18)",
  " (in 'poisson', line 83, column 9 to column 10)",
  " (in 'poisson', line 83, column 2 to column 25)",
  " (in 'poisson', line 84, column 9 to column 10)",
  " (in 'poisson', line 84, column 2 to column 24)",
  " (in 'poisson', line 85, column 9 to column 10)",
  " (in 'poisson', line 85, column 2 to column 45)",
  " (in 'poisson', line 86, column 9 to column 10)",
  " (in 'poisson', line 86, column 2 to column 45)",
  " (in 'poisson', line 92, column 6 to column 117)",
  " (in 'poisson', line 91, column 9 to line 93, column 5)",
  " (in 'poisson', line 90, column 6 to column 44)",
  " (in 'poisson', line 89, column 17 to line 91, column 5)",
  " (in 'poisson', line 89, column 4 to line 93, column 5)",
  " (in 'poisson', line 88, column 15 to line 94, column 3)",
  " (in 'poisson', line 88, column 2 to line 94, column 3)",
  " (in 'poisson', line 98, column 0 to column 13)",
  " (in 'poisson', line 80, column 104 to line 99, column 1)"};
template <typename T0__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,1>
inv_logit2(const T0__& lp_arg__, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              std::is_integral<std::decay_t<T1__>>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,1>
linkinv_poisson(const T0__& lp_arg__, const T1__& link, std::ostream*
                pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              std::is_integral<std::decay_t<T1__>>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,1>
linkinv_bern(const T0__& lp_arg__, const T1__& link, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              std::is_integral<std::decay_t<T3__>>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>>,-1,1>
loglik_poisson(const T0__& y, const T1__& X_arg__, const T2__& beta_arg__,
               const T3__& link1, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              std::is_integral<std::decay_t<T5__>>,
                              std::is_integral<std::decay_t<T6__>>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>>,-1,1>
loglik_zipoisson(const T0__& y, const T1__& X_arg__, const T2__& Z_arg__,
                 const T3__& beta_arg__, const T4__& psi_arg__, const T5__&
                 link1, const T6__& link2, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              std::is_integral<std::decay_t<T5__>>,
                              std::is_integral<std::decay_t<T6__>>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>>,-1,1>
loglik_zapoisson(const T0__& y, const T1__& X_arg__, const T2__& Z_arg__,
                 const T3__& beta_arg__, const T4__& psi_arg__, const T5__&
                 link1, const T6__& link2, std::ostream* pstream__);
// vector inv_logit2(vector)
template <typename T0__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,1>
inv_logit2(const T0__& lp_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& lp = stan::math::to_ref(lp_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 25;
    n = stan::math::num_elements(lp);
    current_statement__ = 26;
    stan::math::validate_non_negative_index("x", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> x =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 30;
    for (int i = 1; i <= n; ++i) {
      current_statement__ = 28;
      stan::model::assign(x, (1 / (1 +
        stan::math::exp(
          -(stan::model::rvalue(lp, "lp", stan::model::index_uni(i)))))),
        "assigning variable x", stan::model::index_uni(i));
    }
    current_statement__ = 31;
    return x;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// vector linkinv_poisson(vector, int)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              std::is_integral<std::decay_t<T1__>>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,1>
linkinv_poisson(const T0__& lp_arg__, const T1__& link, std::ostream*
                pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& lp = stan::math::to_ref(lp_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 39;
    if (stan::math::logical_eq(link, 1)) {
      current_statement__ = 38;
      return stan::math::exp(lp);
    } else {
      current_statement__ = 37;
      if (stan::math::logical_eq(link, 2)) {
        current_statement__ = 36;
        return lp;
      } else {
        current_statement__ = 35;
        if (stan::math::logical_eq(link, 3)) {
          current_statement__ = 34;
          return stan::math::square(lp);
        } else {
          current_statement__ = 33;
          {
            std::stringstream errmsg_stream__;
            stan::math::stan_print(&errmsg_stream__, "Invalid link");
            throw std::domain_error(errmsg_stream__.str());
          }
        }
      }
    }
    current_statement__ = 40;
    return lp;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// vector linkinv_bern(vector, int)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>,
                              std::is_integral<std::decay_t<T1__>>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,1>
linkinv_bern(const T0__& lp_arg__, const T1__& link, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& lp = stan::math::to_ref(lp_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 50;
    if (stan::math::logical_eq(link, 1)) {
      current_statement__ = 49;
      return inv_logit2(lp, pstream__);
    } else {
      current_statement__ = 48;
      if (stan::math::logical_eq(link, 2)) {
        current_statement__ = 47;
        return stan::math::Phi(lp);
      } else {
        current_statement__ = 46;
        if (stan::math::logical_eq(link, 3)) {
          current_statement__ = 45;
          return stan::math::inv_cloglog(lp);
        } else {
          current_statement__ = 44;
          if (stan::math::logical_eq(link, 4)) {
            current_statement__ = 43;
            return stan::math::add(
                     stan::math::divide(stan::math::atan(lp),
                       stan::math::pi()), 0.5);
          } else {
            current_statement__ = 42;
            {
              std::stringstream errmsg_stream__;
              stan::math::stan_print(&errmsg_stream__, "Invalid link");
              throw std::domain_error(errmsg_stream__.str());
            }
          }
        }
      }
    }
    current_statement__ = 51;
    return lp;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// vector loglik_poisson(array[] int, matrix, vector, int)
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              std::is_integral<std::decay_t<T3__>>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>>,-1,1>
loglik_poisson(const T0__& y, const T1__& X_arg__, const T2__& beta_arg__,
               const T3__& link1, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& X = stan::math::to_ref(X_arg__);
  const auto& beta = stan::math::to_ref(beta_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 53;
    n = stan::math::num_elements(y);
    current_statement__ = 54;
    stan::math::validate_non_negative_index("lprob", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lprob =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 56;
    stan::math::validate_non_negative_index("lp1", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp1 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 57;
    stan::model::assign(lp1, stan::math::multiply(X, beta),
      "assigning variable lp1");
    current_statement__ = 58;
    stan::math::validate_non_negative_index("mu", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> mu =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 59;
    stan::model::assign(mu, linkinv_poisson(lp1, link1, pstream__),
      "assigning variable mu");
    current_statement__ = 62;
    for (int i = 1; i <= n; ++i) {
      current_statement__ = 60;
      stan::model::assign(lprob,
        stan::math::poisson_lpmf<false>(
          stan::model::rvalue(y, "y", stan::model::index_uni(i)),
          stan::model::rvalue(mu, "mu", stan::model::index_uni(i))),
        "assigning variable lprob", stan::model::index_uni(i));
    }
    current_statement__ = 63;
    return lprob;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
/* vector
   loglik_zipoisson(array[] int, matrix, matrix, vector, vector, int, int)
 */
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              std::is_integral<std::decay_t<T5__>>,
                              std::is_integral<std::decay_t<T6__>>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>>,-1,1>
loglik_zipoisson(const T0__& y, const T1__& X_arg__, const T2__& Z_arg__,
                 const T3__& beta_arg__, const T4__& psi_arg__, const T5__&
                 link1, const T6__& link2, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>,
                             stan::base_type_t<T4__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& X = stan::math::to_ref(X_arg__);
  const auto& Z = stan::math::to_ref(Z_arg__);
  const auto& beta = stan::math::to_ref(beta_arg__);
  const auto& psi = stan::math::to_ref(psi_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 65;
    n = stan::math::num_elements(y);
    current_statement__ = 66;
    stan::math::validate_non_negative_index("lprob", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lprob =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 68;
    stan::math::validate_non_negative_index("lp1", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp1 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 69;
    stan::model::assign(lp1, stan::math::multiply(X, beta),
      "assigning variable lp1");
    current_statement__ = 70;
    stan::math::validate_non_negative_index("lp2", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp2 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 71;
    stan::model::assign(lp2, stan::math::multiply(Z, psi),
      "assigning variable lp2");
    current_statement__ = 72;
    stan::math::validate_non_negative_index("mu", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> mu =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 73;
    stan::model::assign(mu, linkinv_poisson(lp1, link1, pstream__),
      "assigning variable mu");
    current_statement__ = 74;
    stan::math::validate_non_negative_index("omega", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> omega =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 75;
    stan::model::assign(omega, linkinv_bern(lp2, link2, pstream__),
      "assigning variable omega");
    current_statement__ = 82;
    for (int i = 1; i <= n; ++i) {
      current_statement__ = 80;
      if (stan::math::logical_eq(
            stan::model::rvalue(y, "y", stan::model::index_uni(i)), 0)) {
        current_statement__ = 78;
        stan::model::assign(lprob,
          stan::math::log_sum_exp(
            stan::math::bernoulli_lpmf<false>(0,
              stan::model::rvalue(omega, "omega", stan::model::index_uni(i))),
            (stan::math::bernoulli_lpmf<false>(1,
               stan::model::rvalue(omega, "omega", stan::model::index_uni(i)))
            +
            stan::math::poisson_lpmf<false>(
              stan::model::rvalue(y, "y", stan::model::index_uni(i)),
              stan::model::rvalue(mu, "mu", stan::model::index_uni(i))))),
          "assigning variable lprob", stan::model::index_uni(i));
      } else {
        current_statement__ = 76;
        stan::model::assign(lprob,
          (stan::math::bernoulli_lpmf<false>(1,
             stan::model::rvalue(omega, "omega", stan::model::index_uni(i)))
          +
          stan::math::poisson_lpmf<false>(
            stan::model::rvalue(y, "y", stan::model::index_uni(i)),
            stan::model::rvalue(mu, "mu", stan::model::index_uni(i)))),
          "assigning variable lprob", stan::model::index_uni(i));
      }
    }
    current_statement__ = 83;
    return lprob;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
/* vector
   loglik_zapoisson(array[] int, matrix, matrix, vector, vector, int, int)
 */
template <typename T0__, typename T1__, typename T2__, typename T3__,
          typename T4__, typename T5__, typename T6__,
          stan::require_all_t<stan::is_std_vector<T0__>,
                              std::is_integral<std::decay_t<stan::value_type_t<T0__>>>,
                              stan::is_eigen_matrix_dynamic<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_eigen_matrix_dynamic<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::is_col_vector<T3__>,
                              stan::is_vt_not_complex<T3__>,
                              stan::is_col_vector<T4__>,
                              stan::is_vt_not_complex<T4__>,
                              std::is_integral<std::decay_t<T5__>>,
                              std::is_integral<std::decay_t<T6__>>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T1__>,
                stan::base_type_t<T2__>, stan::base_type_t<T3__>,
                stan::base_type_t<T4__>>,-1,1>
loglik_zapoisson(const T0__& y, const T1__& X_arg__, const T2__& Z_arg__,
                 const T3__& beta_arg__, const T4__& psi_arg__, const T5__&
                 link1, const T6__& link2, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>,
                             stan::base_type_t<T3__>,
                             stan::base_type_t<T4__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& X = stan::math::to_ref(X_arg__);
  const auto& Z = stan::math::to_ref(Z_arg__);
  const auto& beta = stan::math::to_ref(beta_arg__);
  const auto& psi = stan::math::to_ref(psi_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int n = std::numeric_limits<int>::min();
    current_statement__ = 85;
    n = stan::math::num_elements(y);
    current_statement__ = 86;
    stan::math::validate_non_negative_index("lprob", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lprob =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 88;
    stan::math::validate_non_negative_index("lp1", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp1 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 89;
    stan::model::assign(lp1, stan::math::multiply(X, beta),
      "assigning variable lp1");
    current_statement__ = 90;
    stan::math::validate_non_negative_index("lp2", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> lp2 =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 91;
    stan::model::assign(lp2, stan::math::multiply(Z, psi),
      "assigning variable lp2");
    current_statement__ = 92;
    stan::math::validate_non_negative_index("mu", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> mu =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 93;
    stan::model::assign(mu, linkinv_poisson(lp1, link1, pstream__),
      "assigning variable mu");
    current_statement__ = 94;
    stan::math::validate_non_negative_index("omega", "n", n);
    Eigen::Matrix<local_scalar_t__,-1,1> omega =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n, DUMMY_VAR__);
    current_statement__ = 95;
    stan::model::assign(omega, linkinv_bern(lp2, link2, pstream__),
      "assigning variable omega");
    current_statement__ = 102;
    for (int i = 1; i <= n; ++i) {
      current_statement__ = 100;
      if (stan::math::logical_eq(
            stan::model::rvalue(y, "y", stan::model::index_uni(i)), 0)) {
        current_statement__ = 98;
        stan::model::assign(lprob,
          stan::math::bernoulli_lpmf<false>(0,
            stan::model::rvalue(omega, "omega", stan::model::index_uni(i))),
          "assigning variable lprob", stan::model::index_uni(i));
      } else {
        current_statement__ = 96;
        stan::model::assign(lprob,
          (stan::math::bernoulli_lpmf<false>(1,
             stan::model::rvalue(omega, "omega", stan::model::index_uni(i)))
          +
          (stan::math::poisson_lpmf<false>(
             stan::model::rvalue(y, "y", stan::model::index_uni(i)),
             stan::model::rvalue(mu, "mu", stan::model::index_uni(i))) -
          stan::math::log((1 -
            stan::math::exp(
              stan::math::poisson_lpmf<false>(0,
                stan::model::rvalue(mu, "mu", stan::model::index_uni(i)))))))),
          "assigning variable lprob", stan::model::index_uni(i));
      }
    }
    current_statement__ = 103;
    return lprob;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_poisson final : public model_base_crtp<model_poisson> {
private:
  int n;
  int p;
  std::vector<int> y;
  Eigen::Matrix<double,-1,-1> X_data__;
  int link;
  Eigen::Matrix<double,1,-1> x_mean_data__;
  Eigen::Matrix<double,-1,1> x_sd_data__;
  int approach;
  double mu_beta;
  double sigma_beta;
  int log_lik_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,1,-1>> x_mean{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> x_sd{nullptr, 0};
public:
  ~model_poisson() {}
  model_poisson(stan::io::var_context& context__, unsigned int
                random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_poisson_namespace::model_poisson";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 8;
      context__.validate_dims("data initialization", "n", "int",
        std::vector<size_t>{});
      n = std::numeric_limits<int>::min();
      current_statement__ = 8;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "n", n, 1);
      current_statement__ = 9;
      context__.validate_dims("data initialization", "p", "int",
        std::vector<size_t>{});
      p = std::numeric_limits<int>::min();
      current_statement__ = 9;
      p = context__.vals_i("p")[(1 - 1)];
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "p", p, 1);
      current_statement__ = 10;
      stan::math::validate_non_negative_index("y", "n", n);
      current_statement__ = 11;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(n)});
      y = std::vector<int>(n, std::numeric_limits<int>::min());
      current_statement__ = 11;
      y = context__.vals_i("y");
      current_statement__ = 12;
      stan::math::validate_non_negative_index("X", "n", n);
      current_statement__ = 13;
      stan::math::validate_non_negative_index("X", "p", p);
      current_statement__ = 14;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(n), static_cast<size_t>(p)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(n, p,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), n, p);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 14;
        X_flat__ = context__.vals_r("X");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= n; ++sym2__) {
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 15;
      context__.validate_dims("data initialization", "link", "int",
        std::vector<size_t>{});
      link = std::numeric_limits<int>::min();
      current_statement__ = 15;
      link = context__.vals_i("link")[(1 - 1)];
      current_statement__ = 15;
      stan::math::check_greater_or_equal(function__, "link", link, 1);
      current_statement__ = 15;
      stan::math::check_less_or_equal(function__, "link", link, 3);
      current_statement__ = 16;
      stan::math::validate_non_negative_index("x_mean", "p", p);
      current_statement__ = 17;
      context__.validate_dims("data initialization", "x_mean", "double",
        std::vector<size_t>{static_cast<size_t>(p)});
      x_mean_data__ = Eigen::Matrix<double,1,-1>::Constant(p,
                        std::numeric_limits<double>::quiet_NaN());
      new (&x_mean)
        Eigen::Map<Eigen::Matrix<double,1,-1>>(x_mean_data__.data(), p);
      {
        std::vector<local_scalar_t__> x_mean_flat__;
        current_statement__ = 17;
        x_mean_flat__ = context__.vals_r("x_mean");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          stan::model::assign(x_mean, x_mean_flat__[(pos__ - 1)],
            "assigning variable x_mean", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 18;
      stan::math::validate_non_negative_index("x_sd", "p", p);
      current_statement__ = 19;
      context__.validate_dims("data initialization", "x_sd", "double",
        std::vector<size_t>{static_cast<size_t>(p)});
      x_sd_data__ = Eigen::Matrix<double,-1,1>::Constant(p,
                      std::numeric_limits<double>::quiet_NaN());
      new (&x_sd) Eigen::Map<Eigen::Matrix<double,-1,1>>(x_sd_data__.data(),
        p);
      {
        std::vector<local_scalar_t__> x_sd_flat__;
        current_statement__ = 19;
        x_sd_flat__ = context__.vals_r("x_sd");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          stan::model::assign(x_sd, x_sd_flat__[(pos__ - 1)],
            "assigning variable x_sd", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 19;
      stan::math::check_greater_or_equal(function__, "x_sd", x_sd, 0);
      current_statement__ = 20;
      context__.validate_dims("data initialization", "approach", "int",
        std::vector<size_t>{});
      approach = std::numeric_limits<int>::min();
      current_statement__ = 20;
      approach = context__.vals_i("approach")[(1 - 1)];
      current_statement__ = 20;
      stan::math::check_greater_or_equal(function__, "approach", approach, 0);
      current_statement__ = 20;
      stan::math::check_less_or_equal(function__, "approach", approach, 1);
      current_statement__ = 21;
      context__.validate_dims("data initialization", "mu_beta", "double",
        std::vector<size_t>{});
      mu_beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 21;
      mu_beta = context__.vals_r("mu_beta")[(1 - 1)];
      current_statement__ = 22;
      context__.validate_dims("data initialization", "sigma_beta", "double",
        std::vector<size_t>{});
      sigma_beta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 22;
      sigma_beta = context__.vals_r("sigma_beta")[(1 - 1)];
      current_statement__ = 22;
      stan::math::check_greater_or_equal(function__, "sigma_beta",
        sigma_beta, 0);
      current_statement__ = 23;
      stan::math::validate_non_negative_index("beta", "p", p);
      current_statement__ = 24;
      log_lik_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 24;
      log_lik_1dim__ = (stan::math::logical_eq(approach, 1) ? n : 0);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("log_lik",
        "approach == 1 ? n : 0", log_lik_1dim__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = p;
  }
  inline std::string model_name() const final {
    return "model_poisson";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.37.0-rc2",
             "stancflags = --allow-undefined"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_poisson_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p);
      {
        current_statement__ = 4;
        lp_accum__.add(stan::math::sum(
                         loglik_poisson(y, X, beta, link, pstream__)));
        current_statement__ = 7;
        if (stan::math::logical_eq(approach, 1)) {
          current_statement__ = 5;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(beta, mu_beta,
                           sigma_beta));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_poisson_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p);
      {
        current_statement__ = 4;
        lp_accum__.add(stan::math::sum(
                         loglik_poisson(y, X, beta, link, pstream__)));
        current_statement__ = 7;
        if (stan::math::logical_eq(approach, 1)) {
          current_statement__ = 5;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(beta, mu_beta,
                           sigma_beta));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "model_poisson_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(p);
      out__.write(beta);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(log_lik_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      stan::model::assign(log_lik,
        loglik_poisson(y, X, beta, link, pstream__),
        "assigning variable log_lik");
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(p),
        "assigning variable beta");
      out__.write(beta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(p)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(p, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 1;
        beta_flat__ = context__.vals_r("beta");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(p)}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(log_lik_1dim__)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= log_lik_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= p; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= log_lik_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p) + "},\"block\":\"parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_lik_1dim__) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(p) + "},\"block\":\"parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_lik_1dim__) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = p;
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities *
      (log_lik_1dim__);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = p;
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities *
      (log_lik_1dim__);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_poisson_namespace::model_poisson;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_poisson_namespace::profiles__;
}
#endif
#endif
