name: Build and publish R packages to drat

on:
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      # 1️⃣ Clona o repositório do pacote (countmodels)
      - uses: actions/checkout@v4

      # 2️⃣ Clona o repositório drat (marcio-lib) dentro do workspace
      - name: Checkout drat repo
        uses: actions/checkout@v4
        with:
          repository: marcioavbatista/marcio-lib
          path: ./marcio-lib          # 👈 dentro do workspace
          token: ${{ secrets.PERSONAL_TOKEN }}

      # 3️⃣ Instala R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release

      # 4️⃣ Instala dependências
      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("devtools","drat","rcmdcheck"))'

      # 5️⃣ Cria o pacote source
      - name: Build package source
        run: Rscript -e 'devtools::build()'

      # 7️⃣ Insere pacote no drat (Windows → PowerShell)
      - name: Insert package to drat (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          git config --global user.email 'actions@github.com'
          git config --global user.name 'GitHub Actions'
          $r = @'
          library(drat)
          files <- list.files(full.names = TRUE)
          pkg <- files[endsWith(files, ".zip")]
          if (length(pkg) == 0) stop("No tar.gz found")
          insertPackage(pkg,
                        repodir = "marcio-lib/drat",
                        commit = TRUE, push = TRUE,
                        binarize = TRUE)
          '@
          $r | Out-File -Encoding UTF8 insert_to_drat.R
          Rscript insert_to_drat.R
